name: Build and Deploy Azure Functions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure Functions Core Tools
        uses: Azure/functions-action@v1

      - name: Install dependencies
        run: |
          npm install -g azure-functions-core-tools@3 --unsafe-perm true

      - name: Run tests
        run: dotnet test

      - name: Deploy to Azure
        uses: Azure/functions-action@v1
        with:
          app-name: "your-function-app-name"
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
